In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/01_clean_data.csv')

In [3]:
display(df.head())

,Date,home_team,away_team,home_goals,away_goals,match_result,ht_home_goals,ht_away_goals,ht_result,home_shots,away_shots,home_shots_target,away_shots_target,home_red_cards,away_red_cards,B365H,B365D,B365A
0,2025-08-15,Liverpool,Bournemouth,4,2,H,1,0,H,19,10,10,3,0,0,1.30,6.00,8.50
1,2025-08-16,Aston Villa,Newcastle,0,0,D,0,0,D,3,16,3,3,1,0,2.25,3.50,2.90
2,2025-08-16,Brighton,Fulham,1,1,D,0,0,D,10,7,4,2,0,0,1.91,3.60,4.00
3,2025-08-16,Sunderland,West Ham,3,0,H,0,0,D,10,12,5,4,0,0,3.25,3.40,2.25
4,2025-08-16,Tottenham,Burnley,3,0,H,1,0,H,16,14,6,4,0,0,1.38,4.75,8.50

In [4]:
df['home_team_goals_avg_last_5'] = df.groupby('home_team')['home_goals'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['away_goals_avg_last_5'] = df.groupby('away_team')['away_goals'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['ht_home_goals_avg_last_5'] = df.groupby('home_team')['ht_home_goals'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['ht_away_goals_avg_last_5'] = df.groupby('away_team')['ht_away_goals'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))

In [5]:
df['home_balance_1h'] = df['ht_home_goals'] - df['ht_away_goals']
df['home_balance_2h'] = (df['home_goals'] - df['ht_home_goals']) - (df['away_goals'] - df['ht_away_goals'])
df['away_balance_1h'] = -df['home_balance_1h']
df['away_balance_2h'] = -df['home_balance_2h']

In [6]:
df['home_form_1h_last_5'] = df.groupby('home_team')['home_balance_1h'].transform(lambda x: x.rolling(5, min_periods=1).mean().shift(1))
df['away_form_1h_last_5'] = df.groupby('away_team')['away_balance_1h'].transform(lambda x: x.rolling(5, min_periods=1).mean().shift(1))
df['home_form_2h_last_5'] = df.groupby('home_team')['home_balance_2h'].transform( lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['away_form_2h_last_5'] = df.groupby('away_team')['away_balance_2h'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))

In [7]:
display(df.head())

,Date,home_team,away_team,home_goals,away_goals,match_result,ht_home_goals,ht_away_goals,ht_result,home_shots,...,ht_home_goals_avg_last_5,ht_away_goals_avg_last_5,home_balance_1h,home_balance_2h,away_balance_1h,away_balance_2h,home_form_1h_last_5,away_form_1h_last_5,home_form_2h_last_5,away_form_2h_last_5
0,2025-08-15,Liverpool,Bournemouth,4,2,H,1,0,H,19,...,NaN,NaN,1,1,-1,-1,NaN,NaN,NaN,NaN
1,2025-08-16,Aston Villa,Newcastle,0,0,D,0,0,D,3,...,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN
2,2025-08-16,Brighton,Fulham,1,1,D,0,0,D,10,...,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN
3,2025-08-16,Sunderland,West Ham,3,0,H,0,0,D,10,...,NaN,NaN,0,3,0,-3,NaN,NaN,NaN,NaN
4,2025-08-16,Tottenham,Burnley,3,0,H,1,0,H,16,...,NaN,NaN,1,2,-1,-2,NaN,NaN,NaN,NaN

In [8]:
df['home_shots_avg_last_5'] = df.groupby('home_team')['home_shots'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['away_shots_avg_last_5'] = df.groupby('away_team')['away_shots'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))

In [9]:
df['home_shots_target_avg_last_5'] = df.groupby('home_team')['home_shots_target'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['away_shots_target_avg_last_5'] = df.groupby('away_team')['away_shots_target'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))

In [10]:
df['home_red_cards_avg_last_5'] = df.groupby('home_team')['home_red_cards'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['away_red_cards_avg_last_5'] = df.groupby('away_team')['away_red_cards'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))

In [11]:
df['home_goals_conceded_avg_last_5'] = df.groupby('home_team')['away_goals'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['away_goals_conceded_avg_last_5'] = df.groupby('away_team')['home_goals'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))

In [12]:
df['target'] = df['match_result'].map({'H': 2, 'D': 1, 'A': 0})

In [13]:
df['home_points'] = df['match_result'].map({'H': 3, 'D': 1, 'A': 0})
df['away_points'] = df['match_result'].map({'H': 0, 'D': 1, 'A': 3})

In [14]:
df['home_points_avg_last_5'] = df.groupby('home_team')['home_points'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))
df['away_points_avg_last_5'] = df.groupby('away_team')['away_points'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))

In [15]:
df_home_points = df[['Date', 'home_team', 'home_points']].copy()
df_away_points = df[['Date', 'away_team', 'away_points']].copy()
df_home_points.columns = ['Date', 'Team', 'Points']
df_away_points.columns = ['Date', 'Team', 'Points']
concatenated_points = pd.concat([df_home_points, df_away_points], ignore_index=True)
concated_points_sorted = concatenated_points.sort_values(by=['Team', 'Date'])
concated_points_sorted['overall_points_last_5'] = concated_points_sorted.groupby('Team')['Points'].transform(lambda x: x.rolling(window=5, min_periods=1).mean().shift(1))

In [16]:
df = df.merge(
    concated_points_sorted[['Date', 'Team', 'overall_points_last_5']],
    left_on=['Date', 'home_team'],   
    right_on=['Date', 'Team'],       
    how='left'
)
df = df.drop(columns=['Team'])
df = df.rename(columns={'overall_points_last_5': 'home_overall_points_last_5'})

df = df.merge(
    concated_points_sorted[['Date', 'Team', 'overall_points_last_5']],
    left_on=['Date', 'away_team'],
    right_on=['Date', 'Team'],
    how='left'
)
df = df.drop(columns=['Team'])
df = df.rename(columns={'overall_points_last_5': 'away_overall_points_last_5'})

In [17]:
print(",".join(df.columns.to_list()))

Date,home_team,away_team,home_goals,away_goals,match_result,ht_home_goals,ht_away_goals,ht_result,home_shots,away_shots,home_shots_target,away_shots_target,home_red_cards,away_red_cards,B365H,B365D,B365A,home_team_goals_avg_last_5,away_goals_avg_last_5,ht_home_goals_avg_last_5,ht_away_goals_avg_last_5,home_balance_1h,home_balance_2h,away_balance_1h,away_balance_2h,home_form_1h_last_5,away_form_1h_last_5,home_form_2h_last_5,away_form_2h_last_5,home_shots_avg_last_5,away_shots_avg_last_5,home_shots_target_avg_last_5,away_shots_target_avg_last_5,home_red_cards_avg_last_5,away_red_cards_avg_last_5,home_goals_conceded_avg_last_5,away_goals_conceded_avg_last_5,target,home_points,away_points,home_points_avg_last_5,away_points_avg_last_5,home_overall_points_last_5,away_overall_points_last_5

In [18]:
df.to_csv('../data/features_data.csv', index=False)